import pyautogui
import time
import pyperclip
pyautogui.moveTo(759,877)
pyautogui.click()
time.sleep(5)
pyautogui.moveTo(597,107)
pyautogui.click()
time.sleep(10)
pyautogui.moveTo(93,628)
pyautogui.click()
time.sleep(5)
pyautogui.moveTo(278,222)
pyautogui.click()
time.sleep(5)
pyautogui.moveTo(550,784)
pyautogui.click()
time.sleep(5)
pyperclip.copy("pyautoguiで送付しています")
pyautogui.hotkey('ctrl', 'v')
time.sleep(5)
pyautogui.moveTo(891,834)
pyautogui.click()
